### ISSUE TITLE
Create a CLI project in the monorepo using Deno

### ISSUE THREAD

**Issue by mfero** [TeselaGen/fsml.org#10]
Create a CLI project using Deno and Nx monorepo workspaces.

[Deno](https://deno.land/) - Deno is the "next" iteration of [Node.js](https://deno.land/manual/node/dnt). It provides native TypeScript and es6 support. It's compatible with Node.js and supports isomorphic (runs on back and front end) code. Finally it has the advantage of being able to target all major OS's and compile to a [single executable](https://deno.land/manual/tools/compiler) / CLI tool.

[Nx](https://nx.dev/) - for monorepo support. Nx is fairly platform agnostic however it is missing tooling for https://github.com/nrwl/nx/discussions/5823 which we'll need to provide as plugins.

Example Deno CLI projects

- https://dev.to/unorthodev/build-a-simple-cli-tool-with-deno-1fmk
- https://startfunction.com/2020/07/03/how-to-create-deno-cli-tool/
- https://www.twilio.com/blog/use-deno-build-cli
- https://levelup.gitconnected.com/build-a-cli-tool-deno-by-example-79d39f25eb0a
- https://www.loginradius.com/blog/engineering/build-a-cli-tool-using-deno/

**Comment by eabeliuk** [comment]
@tgadam , let's discuss this one. It seems that we can mark this as completed too.

**Comment by AndresPerezTesela** [comment]
Design in https://github.com/TeselaGen/fsml.org/issues/35 and implemented in https://github.com/TeselaGen/fsml.org/issues/85
