### ISSUE TITLE
Create JSON Specifications for the Manifest file

### ISSUE THREAD

**Issue by mfero** [TeselaGen/fsml.org#11]
I propose using TypeBox with Deno to create the specification. Then compile that library to WASM for use in other languages such as Python.

The current draft specification is documented on the website fsml.org.

TypeBox - TypeBox is a type validation system built on TypeScript and JSON Schema. It provides the ability to have static (or transpile time) TypeScript validation of types as well as runtime JSON Schema validation of types. It can also generate a https://github.com/sinclairzx81/typebox/issues/143 from the TypeScript types. It's available for both [Node.js](https://github.com/sinclairzx81/typebox) and [Deno](https://deno.land/x/typebox@0.23.4).

**Comment by eabeliuk** [comment]
@tgadam let's discuss this one whenever you have a chance.

**Comment by AndresPrez** [comment]
Using Deno, TypeBox APIs need to be imported via esm.sh https://github.com/sinclairzx81/typebox/issues/216

**Comment by AndresPerezTesela** [comment]
https://github.com/TeselaGen/fsml.org/issues/31
