### ISSUE TITLE
Reorganize GitHub pages website

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#17]
Currently the GitHub pages site is on a separate branch and hosted from the root of the repo. I think in order to facilitate auto generated documentation on the website we should merge it into the main branch and put it in a subfolder.

Additionally I plan to rename the repo to all lowercase to match the patter of our other repos.

- [x] Move into website folder
- [x] Merge into main
- [x] Rename lowercase

**Comment by tgadam** [comment]
Currently setting up a Gatsby template based on Hasura docs.

**Comment by eabeliuk** [comment]
@tgadam is this one completed?
