### ISSUE TITLE
Research and choose a graph layout tool

### ISSUE THREAD

**Issue by mfero** [TeselaGen/FSML.org#2]
Daniel Bryce at SIFT.net has created a nice alpha for a directed graph style protocol editor for PAML (see screenshot). We should investigate tooling that fits better with our pretty-much pure JS development environment. @tgadam has suggested the following:

- https://js.cytoscape.org/#introduction
- https://github.com/uber/react-digraph
- https://reactflow.dev/
- https://github.com/projectstorm/react-diagrams

Let's check them out and pick one to move forward as a provisional choice by the next BioMADE meeting on Feb 25.

**Dan's visualization of a 96-96 well plate stamp:**
<img width="927" alt="image" src="https://user-images.githubusercontent.com/7561861/154780014-190d24d7-6563-419f-8865-29f6c45a6081.png">

**Comment by eabeliuk** [comment]
Had a meeting last week on this. Making progress.

**Comment by tgadam** [comment]
@tgreen7 and @christopher-lamkin has been trying React Flow. The current focus is seeing if it could handle multiple input and output connector ports per node.

**Comment by mfero** [comment]
@tgreen7 is proposing React Flow, it seems to be presenting basic graphs nicely.
![image](https://user-images.githubusercontent.com/7561861/159065227-06bd09ff-2c4a-4955-9faa-74057e0eec07.png)

**Comment by mfero** [comment]
@tgreen7 perhaps we list some of the boxes we think this tool will check off?

- [ ] Can represent a basic acyclic directed graphs
- [ ] Can accommodate multiple inputs and outputs (a la Node-RED graphs)
- [ ] Can be viewed vertically or horizontally
- [ ] Can be zoomed and moved within a view
- [ ] Has a snap-to grid function for box size and location
- [ ] Has ability to move connector to different locations on the node (optional)
- [ ] Has an auto-layout function
- [ ] Compatible with generating exportable graphical representations (.pdf, .png, .svg)

**Comment by mfero** [comment]
I think we have provisionally chosen React Flow, So I'll close this.
