### ISSUE TITLE
Create Deno SDK (package) that provides manifest generation and validation functionality

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#30]
The manifest schema is stored in the spec package. We need a package that will contain the functionality to use the schema to both generate and validate the schema.

We want this package to be isomorphic so it needs to not have any server or web specific dependencies such file system libraries. Instead data should be passed to this package as a stream.

**Comment by eabeliuk** [comment]
@AndresPerezTesela is finishing implementing an enhancement that would allow the user to validate against the schema.

**Comment by eabeliuk** [comment]
From nodeRed we can generate and validate a manifest. Closing this ticket
