### ISSUE TITLE
Develop the first draft of the data schema for FSML

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#31]
We've proposed a draft for the exchange protocols and now we need to expand upon that to also support exchanging data generated by those protocols such as execution traces and workflow runs.

We should take our existing Test Data Model and convert it into a standard.

**Comment by AndresPrez** [comment]
Making progress in #78 

Im not sure about a lot of things yet but let's talk about it

**Comment by tgadam** [comment]
In progress  @AndresPerezTesela and @tgadam  need to have a further discussion about the proposed examples.
