### ISSUE TITLE
Create Plugin System for CLI using Dynamic Imports

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#60]
Create Plugin System for CLI using Dynamic Imports. Example https://medium.com/deno-the-complete-reference/dynamic-imports-in-deno-5e9eb7f66238

**Comment by tgadam** [comment]
@juanneilson we shared pair and discuss this further.

**Comment by tgadam** [comment]
@juanneilson feel free to hand this off to someone else

**Comment by eabeliuk** [comment]
@AndresPerezTesela could be looking into this ticket, but will chat with @tnrich too.

**Comment by eabeliuk** [comment]
We are having challenges using dynamic imports and compiling to a single executable using with deno.

**Comment by eabeliuk** [comment]
A little bit more research is needed. High priority to this ticket.

**Comment by AndresPerezTesela** [comment]
Notes on:

- **Javy**: Shopify's beta JS to WASM tool. _It's still in beta, error handling isnt very user friendly and requires close to advance knowledge in software development_

- **nexe/nexe**: Node to executable tool.
   - Supports up to node v14.15.3 (there are some releases after that but are buggy)
   - 

- **vercel/pkg**: Node to executable tool

**Comment by tgadam** [comment]
Here are some additional thoughts from discussions we've had around this:

### Background:
Deno was originally selected because it supports dynamic and remote imports. This would enable people extending the tools to create and host their plugins anywhere on the internet and the tools could download the plugins on-demand over the network. Deno was also selected because it would compile to a single executable that targeted all major platforms making installation low effort and avoid any potential issues regarding runtime version mismatches. 

It was only recently discovered that these two features dynamic imports and compiled executables are not compatible together in Deno. If you use dynamic imports then you can't compile to a single executable. 

This means we have to adjust our approach either regarding installation or regarding extensibility.

### Additional Options
In addition to the options explored above we've also discussed but not evaluated:

- Using a 3rd party installer to package the entire Deno runtime with the code into a single file.
- Creating or adopting a DSL (domain specific language) for plugins and implementing an interpreter for the DSL in the tools.
- Making the plugin framework essentially a "shell" runner. Meaning that plugin authors would need to package their plugins up as single exe's as well and then we would download them and run through as separate processes.

**Comment by tgadam** [comment]
We're going to move forward with Deno and figure out a way to build our own installation packages.

**Comment by AndresPrez** [comment]
Had this branch made where deno is ditched in favour of typescript in case we decide to go back in the future: https://github.com/TeselaGen/fsml.org/tree/refactor/ap/deno-out-ts-in

**Comment by cowboyd** [comment]
@tgadam This is a real problem for us in the CLI that we are developing for Deno as well. At a minimum would love to find out about any solution you come up with, but also we're open to collaborating on it if you want help.

**Comment by tgadam** [comment]
> @tgadam This is a real problem for us in the CLI that we are developing for Deno as well. At a minimum would love to find out about any solution you come up with, but also we're open to collaborating on it if you want help.

@cowboyd for now we're thinking of adapting the packaging and installation scripts that OClif uses for Deno.

**Comment by tgadam** [comment]
We're close to having a plugin framework and example Microbyre plugin working

**Comment by cowboyd** [comment]
@tgadam sounds amazing. I'm very curious how you ended up loading your plugins dynamically.

**Comment by tgadam** [comment]
> @tgadam sounds amazing. I'm very curious how you ended up loading your plugins dynamically.

@cowboyd we used Deno's dynamic import. Here's an article that is a good starting point https://medium.com/deno-the-complete-reference/dynamic-imports-in-deno-5e9eb7f66238

**Comment by cowboyd** [comment]
Ah I see, and then bundle Deno itself using the OClif style packaging.... makes sense.

**Comment by eabeliuk** [comment]
Making progress with the plugin systems. Some preliminary tests are being run with the Microbyre dataset/plugin
