### ISSUE TITLE
Develop examples using real world fermentation data

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#73]
We need to develop a couple of examples demonstrating converting source (aka raw) fermentation data into the FSML data standard.

- [x] Develop a public facing example that can be stored in fsml.org
- [x] Develop an example using partner data

**Comment by eabeliuk** [comment]
Here is an interesting example that we might use: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5320064/#bib1

**Comment by tgadam** [comment]
Identified some partner data that we can use. The above link has a large volume of data that would be a good complete public example but it's pretty dense so it may not be a good intro dataset.

Still searching for a good intro public dataset.

**Comment by eabeliuk** [comment]
We can use this dataset: https://abpdu.lbl.gov/resources/fermentation-bioreactor-sample-data/

**Comment by tgadam** [comment]
@mfero is seeing if we can use our previously identified partner example as a public example.

**Comment by mfero** [comment]
Yes, this is public.

**Comment by eabeliuk** [comment]
@mfero to check if we could randomize the values in the csv files from Microbyre.

**Comment by eabeliuk** [comment]
@AndresPerezTesela to check if we can select some data from the ABPDU dataset, as a working example.

**Comment by eabeliuk** [comment]
@mfero still to check with Microbyre about randomizing their csv files.

**Comment by eabeliuk** [comment]
@AndresPerezTesela Could you add some links here pointing to the datasets to be used as an interim example?

**Comment by AndresPerezTesela** [comment]
AMBR Data is dispersed in many different files. I've created this folder with AMBR's public data and start putting something together: https://drive.google.com/drive/u/0/folders/1db63-5T3skv6nfF6C-ehR1SQyymh4iHW

**Comment by AndresPerezTesela** [comment]
Seems like we have an real MicroByre example to use. Closing ticket for now.
