### ISSUE TITLE
Merging PR's unrelated to the website cause website PR previews to get deleted

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#81]
Merging PR's unrelated to the website cause website PR previews to get deleted. When we merged https://github.com/TeselaGen/fsml.org/pull/78 which only had changes in the `packages/` folder, it still triggered the website deploy and it deleted the `pr-preview/` folder in the gh-pages branch https://github.com/TeselaGen/fsml.org/commit/7d5a4592beda3369e7ff8623b196e2363f846993.

**Comment by tgadam** [comment]
@tgreen7 any idea what's going on here?

**Comment by eabeliuk** [comment]
@tgreen7 still checking this issue.

**Comment by tgreen7** [comment]
This should be fixed now that we moved to a different deploy action. The old deploy action was wiping the pr-preview folder. All old prs will still be broken.
