### ISSUE TITLE
Implement CLI Command to generate manifest for fermentation data

### ISSUE THREAD

**Issue by tgadam** [TeselaGen/fsml.org#82]
Implement CLI Command to generate manifest for fermentation data.

Depends on #35 and #30 

This ticket would generate a manifest that implements the generation of a manifest for a data files that don't get parsed.

**Comment by eabeliuk** [comment]
We will use Microbyre data to test CLI. Relates to #83 .

**Comment by eabeliuk** [comment]
We identify issues with Deno that will force us to refactor the plugin framework. This ticket will have to wait until we implement such refactoring.

**Comment by AndresPerezTesela** [comment]
Issues with Deno have been overcome.
